### ISSUE TITLE
fix get_ttvs_nodata

### ISSUE THREAD

**Issue by kemasuda** [kemasuda/jnkepler#8]
get_ttvs_nodata sometimes returns NaNs for non-coplanar orbits. This does not cause issues in fitting because get_ttvs (fitted) works fine, but is inconvenient for plotting.

**Comment by kemasuda** [comment]
Wrote a modified (jitted) function get_transit_times_all. Need to update
- plot_models
- check_timing_precision
- sample_means_and_stds

**Comment by ericagol** [comment]
At some point it might be nice if we could carry out a detailed comparison with NbodyGradient.jl.

**Comment by kemasuda** [comment]
> At some point it might be nice if we could carry out a detailed comparison with NbodyGradient.jl.

Yes, that would be useful. I've opened a new issue for this, so please feel free to add any ideas for tests.

**Comment by kemasuda** [comment]
Pushed fix to develop branch. Replaced non-jittable get_ttvs_nodata with jittable version get_transit_times_all.

**Comment by kemasuda** [comment]
Pushed to main branch.
